# .github/workflows/ci.yml
name: Java Build and Custom Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Temurin JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # 🔨 Build phase
    - name: Build with Maven (no tests)
      run: mvn clean install -DskipTests

    # 🧪 Custom test phase
    - name: Run specific tests
      run: mvn -f  tests/my-tests/pom.xml -e test

